version: '3.9'
services:
  geodata-db:
    image: "postgis/postgis:16-3.4-alpine"
    container_name: gis_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: geodata1234
    volumes:
      - ./databaseData:/var/lib/postgresql/data
    networks:
      - gis-network
    ports:
      - "5444:5432"

networks:
  gis-network:
    driver: bridge

