version: '3.9'

services:
  geodata-db:
    image: "postgis/postgis:16-3.4-alpine"
    container_name: gis_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: geodata1234
    volumes:
      - ./databaseData:/var/lib/postgresql/data
    networks:
      - gis-network
    ports:
      - "5444:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8989 --reload
    volumes:
      - ./app:/app
    ports:
      - "8989:8989"
    depends_on:
      - geodata-db
#    environment:
#        - DB_URL=postgresql://postgres_user:geodata1234@gis_postgres:5432/postgres
    networks:
      - gis-network

networks:
  gis-network:
    driver: bridge